platform :ios, "7.0"
workspace 'Nests'
pod 'CocoaLumberjack', '~> 2.0.0-rc'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'JSONKit', '~> 1.5pre'
pod 'MBProgressHUD', '~> 0.9'
pod 'UIAlertView+Blocks', '~> 0.8.1'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'UIActionSheet+Block', '~> 1.0.2'
pod 'CSStickyHeaderFlowLayout'
pod 'BButton'
pod 'GBFlatButton'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'Masonry', '~> 0.6.1'
pod 'KVOController', '~> 1.0.3'
pod 'SDWebImage', '~> 3.7.1'
pod 'CHDropDownTextField', '~> 1.0.0'
pod 'FMDB', '~> 2.5'
pod 'HMSegmentedControl', '~> 1.5'
pod 'DLStarRating', '~> 1.1'
pod 'RSKImageCropper', '~> 1.1.2'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'RESideMenu', '~> 4.0.7'
pod 'XGPush', '~> 2.3'
pod 'AMap3DMap', '~> 3.2.1'
pod 'AMapSearch', '~> 3.1.0'
pod 'AMapLocation', '~> 1.0.1'
pod 'HCSStarRatingView', '~> 1.4.3'
pod 'EAIntroView', '~> 2.7.0'
pod 'MOBFoundation_IDFA', '~> 1.2.2'
pod 'SMSSDK', '~> 2.0.0'


